#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2021/9/9 11:11 下午
# @Author : LeiXueWei
# @CSDN/Juejin/Wechat: 雷学委
# @XueWeiTag: CodingDemo
# @File : template.py
# @Project : pypi_seed



TEMPLATE = """
from distutils.core import setup
from setuptools import find_packages

setup(name='%s',  ## 包名
      version='0.0.1',  ## 版本号
      description='Sample project generated by pypi_seed', ##项目描述信息
      long_description="Powered by py4ever team!",
      author='%s', ##作者
      author_email='youremail@qq.com', ##邮箱
      url='your-professional-site', ##这个库的介绍链接，也可以库的开发者网站
      install_requires=[],
      license='Apache License 2.0', ##许可证类型
      packages=find_packages(),
      platforms=["all"],
      classifiers=[
          'Intended Audience :: Developers',
          'Operating System :: OS Independent',
          'Natural Language :: Chinese (Simplified)',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.8',
          'Programming Language :: Python :: 3.9',
          'Topic :: Software Development :: Libraries'
      ],
      )
"""

README = """
# %s

Please change the description here (for your project)

这里需要改成自己的项目信息，比如：一个pypi的项目模板（种子项目）


Powered by [pypi-seed](https://pypi.org/project/pypi-seed/)

# More Info 
Author %s
"""


README_RST_TEMPLATE = """
%s
=========

Please change the description here (for your project)

这里需要改成自己的项目信息，比如：一个pypi的项目模板（种子项目）

Package hosted on [`pypi`_] and powered by [`pypi-seed`_]

Installation / 安装
--------------------------

::

    pip install %s


More Info 
--------------------------

Author %s

.. _`pypi`: https://pypi.org/
.. _`pypi-seed`: https://pypi.org/project/pypi-seed/

"""

